#!/usr/bin/env bash

echo "Loading ~/.bash_profile"
echo "Logged in as $USER at $(hostname)"

source ~/.bashrc

export PATH="$HOME/.poetry/bin:$PATH"
[[ -e "$HOME/.asdf/asdf.sh" ]] && . "$HOME/.asdf/asdf.sh" 
[[ -e "$HOME/.asdf/completions/asdf.bash" ]] && . "$HOME/.asdf/completions/asdf.bash"
