# Probably too specific to install all of this unless you know what you are doing
cask_args appdir: '/Applications'
tap 'homebrew/cask-fonts'

brew 'git'
brew 'bash'
brew 'zsh'
brew 'macvim'

# unix stuff
brew 'openssl'
brew 'libyaml' # should come after openssl
brew 'git'

# services & DBs
brew 'postgresql@14'
brew 'redis'
brew 'sqlite'

# languages
# https://github.com/pyenv/pyenv/wiki/Common-build-problems
brew 'readline'
brew 'xz'

brew 'asdf'
 brew 'openjdk'
# brew 'scala'

# general tools
brew 'hub'
brew 'gh'
brew 'watchman'
brew 'the_silver_searcher'
brew 'trash'
brew 'blueutil'

# Apps

cask 'font-fira-code'
cask 'font-monoid'
