#!/usr/bin/env bash

function _update_ps1() {
  if type "powerline-shell" &> /dev/null; then
    PS1=$(powerline-shell $?)
  fi
}

if [ "$TERM" != "linux" ]; then
  PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
